### PR TITLE
Fix Docker Compose Usage with 1.x Branch

### PR DESCRIPTION
**Pull request by RobLoach**
This just makes it work with 1.x. We should later on update to 2.x.

### CODE REVIEW

**Comment by gremy** [comment]
https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml

**Comment by RobLoach** [comment]
@gremy Updating the yml file should likely go over here: https://github.com/kalamuna/drupal-project/pull/21

**Comment by RobLoach** [comment]
This just makes it work with 1.x. We could update it to 2.x, but would like to take that on in a different PR.

**Comment by gremy** [comment]
Makes sense

**Pull request merged**
